name: veropen

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PORT: ${HTTP_PORT}
        HTTPS_PORT: ${HTTPS_PORT}
    env_file:
      - .env.docker
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - HTTPS_PORT=${HTTPS_PORT}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - PGHOST=${PGHOST}
      - PGUSER=${PGUSER}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${HTTPS_PORT}:${HTTPS_PORT}"
    volumes:
      - ./server/public/uploads:/app/server/public/uploads
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:latest
    env_file:
      - .env.docker
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - "${PGPORT}:${PGPORT}"
    volumes:
      - db_data:/var/lib/postgres/data

volumes:
  db_data: {}
